/*DSW - Create New Tablespaces*/

--#SET TERMINATOR @

BEGIN
    IF NOT EXISTS (
         select 1 from syscat.tablespaces where  tbspace='IBMQUOTESTS' ) THEN
    
        EXECUTE IMMEDIATE 'CREATE LARGE TABLESPACE "IBMQUOTESTS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP
            PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE
            USING STOGROUP "IBMSTOGROUP"
            AUTORESIZE YES
            INITIALSIZE 32 M
            INCREASESIZE 30 PERCENT
            MAXSIZE NONE
            EXTENTSIZE 32
            PREFETCHSIZE 32
            BUFFERPOOL "BPTABLE"
            DATA TAG INHERIT
            OVERHEAD 24.100000
            TRANSFERRATE 0.140000
            NO FILE SYSTEM CACHING
            DROPPED TABLE RECOVERY ON';
     END IF;
       IF NOT EXISTS (
         select 1 from syscat.tablespaces where  tbspace='IBMQUOTESIS' ) THEN
    
        EXECUTE IMMEDIATE 'CREATE LARGE TABLESPACE "IBMQUOTESIS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP
            PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE
            USING STOGROUP "IBMSTOGROUP"
            AUTORESIZE YES
            INITIALSIZE 32 M
            INCREASESIZE 30 PERCENT
            MAXSIZE NONE
            EXTENTSIZE 32
            PREFETCHSIZE 32
            BUFFERPOOL "BPTABLE"
            DATA TAG INHERIT
            OVERHEAD 24.100000
            TRANSFERRATE 0.140000
            NO FILE SYSTEM CACHING
            DROPPED TABLE RECOVERY ON';
     END IF;
       IF NOT EXISTS (
         select 1 from syscat.tablespaces where  tbspace='IBMSALESORDTS' ) THEN
    
        EXECUTE IMMEDIATE 'CREATE LARGE TABLESPACE "IBMSALESORDTS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP
            PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE
            USING STOGROUP "IBMSTOGROUP"
            AUTORESIZE YES
            INITIALSIZE 32 M
            INCREASESIZE 30 PERCENT
            MAXSIZE NONE
            EXTENTSIZE 32
            PREFETCHSIZE 32
            BUFFERPOOL "BPTABLE"
            DATA TAG INHERIT
            OVERHEAD 24.100000
            TRANSFERRATE 0.140000
            NO FILE SYSTEM CACHING
            DROPPED TABLE RECOVERY ON';
     END IF;
       IF NOT EXISTS (
         select 1 from syscat.tablespaces where  tbspace='IBMSALESORDIS' ) THEN
    
        EXECUTE IMMEDIATE 'CREATE LARGE TABLESPACE "IBMSALESORDIS" IN DATABASE PARTITION GROUP IBMDEFAULTGROUP
            PAGESIZE 4096 MANAGED BY AUTOMATIC STORAGE
            USING STOGROUP "IBMSTOGROUP"
            AUTORESIZE YES
            INITIALSIZE 32 M
            INCREASESIZE 30 PERCENT
            MAXSIZE NONE
            EXTENTSIZE 32
            PREFETCHSIZE 32
            BUFFERPOOL "BPTABLE"
            DATA TAG INHERIT
            OVERHEAD 24.100000
            TRANSFERRATE 0.140000
            NO FILE SYSTEM CACHING
            DROPPED TABLE RECOVERY ON';
     END IF;
     

END @

SET SERVEROUTPUT OFF@
--#SET TERMINATOR ;
