/*DSW - Create Sales Order Tables*/

--#SET TERMINATOR @

BEGIN
    IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_SALES_ORDERS' and tabschema='SCTID' ) THEN 

			EXECUTE IMMEDIATE 'CREATE TABLE SCTID.IBM_SALES_ORDERS  (
						  ID CHAR(36 ) NOT NULL , 
						  NAME CHAR(36 ) NOT NULL , 
						  DELETED SMALLINT NOT NULL , 
						  CREATED_BY CHAR(36 ) , 
						  MODIFIED_USER_ID CHAR(36 ) , 
						  ASSIGNED_USER_ID CHAR(36 ) , 
						  SUBMITTER_ID CHAR(36 ) , 
						  DATE_ENTERED TIMESTAMP , 
						  DATE_MODIFIED TIMESTAMP , 
						  ADD_DATE TIMESTAMP , 
						  AGRMT_TYPE_CODE CHAR(4 ) , 
						  AGRMT_TYPE_CODE_DSCR VARCHAR(40 ) , 
						  CMR_SYS_LOC_CODE VARCHAR(3 ) , 
						  CNTRY_CODE CHAR(3 ) , 
						  CNTRY_CODE_2 CHAR(5 ) , 
						  CREATOR_CNUM CHAR(36 ) , 
						  CREATOR_ID VARCHAR(256 ) , 
						  CURRNCY_CODE CHAR(3 ) , 
						  CUST_NAME_FULL VARCHAR(536 ) , 
						  IBM_CLIENT_NUM CHAR(10 ) NOT NULL , 
						  IBM_CUST_NUM VARCHAR(10 ) , 
						  IDM_CNT_ID_TECH VARCHAR(100 ) , 
						  IDM_CNT_ID_SOLD_TO VARCHAR(100 ) , 
						  IDM_QUOTE_CNT_ID VARCHAR(100 ) , 
						  LINE_OF_BUS_CODE CHAR(2 ) , 
						  LOCAL_EXTND_PRICE_TOT DECIMAL(19,4) , 
						  MOD_DATE TIMESTAMP , 
						  OPPRTNTY_NUM CHAR(36 ) , 
						  OPPRTNTY_OWNR_EMAIL_ADR VARCHAR(256 ) , 
						  PRECDNG_DOC_NUM CHAR(10 ) , 
						  PROVISNG_HOLD_FLAG CHAR(1 ) , 
						  QUOTE_CNT_ID INTEGER , 
						  QUOTE_NUM CHAR(36 ) , 
						  SALES_ORD_BILLD_FLAG CHAR(1 ) , 
						  SAP_CNT_ID_SOLD_TO DECIMAL(10,0) , 
						  SAP_CNT_ID_TECH DECIMAL(10,0) , 
						  SAP_CTRCT_NUM CHAR(10 ) , 
						  SAP_OVRL_STAT_CODE CHAR(8 ) , 
						  SAP_OVRL_STAT_CODE_DSCR VARCHAR(40 ) , 
						  SOLD_TO_CUST_NUM CHAR(10 ) , 
						  SAP_ODS_MOD_DATE TIMESTAMP , 
						  SUBMITTR_EMAIL VARCHAR(256 ) , 
						  SUBMITTR_CNUM CHAR(36 ) , 
						  TRIAL_ID VARCHAR(100 ) , 
						  LAST_UPDATING_SYSTEM_DATE TIMESTAMP NOT NULL , 
						  LAST_UPDATING_SYSTEM CHAR(50 ) NOT NULL , 
						  WEB_QUOTE_NUM CHAR(36 ) )   
				  	  	  COMPRESS YES
				                  DATA CAPTURE CHANGES
				                  IN IBMSALESORDTS  INDEX IN IBMSALESORDIS
						  ORGANIZE BY ROW'; 
				
				EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBMSALESORDPK ON SCTID.IBM_SALES_ORDERS (ID ASC) COMPRESS YES  ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS ';
				
				EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_SALES_ORDERS  ADD CONSTRAINT IBMSALESORDPK PRIMARY KEY (ID)';
	END IF;
				
				

    IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_SALES_ORDERS_ACCOUNTS' and tabschema='SCTID' ) THEN 
				
		EXECUTE IMMEDIATE 'CREATE TABLE SCTID.IBM_SALES_ORDERS_ACCOUNTS  (
				  ID VARCHAR(36 ) NOT NULL , 
				  ORDER_ID CHAR(36 ) NOT NULL , 
				  ACCOUNT_ID CHAR(36 ) , 
				  DATE_ENTERED TIMESTAMP , 
				  DATE_MODIFIED TIMESTAMP , 
				  DELETED SMALLINT NOT NULL )   
		  	  	  COMPRESS YES
		                  DATA CAPTURE CHANGES
		                  IN IBMSALESORDTS  INDEX IN IBMSALESORDIS
				 ORGANIZE BY ROW'; 
		
		
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBM_SORD_ACC_PK ON SCTID.IBM_SALES_ORDERS_ACCOUNTS (ID ASC) COMPRESS YES ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS ';
		EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_SALES_ORDERS_ACCOUNTS ADD CONSTRAINT IBM_SORD_ACC_PK PRIMARY KEY	(ID)';

END IF;


    IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_SALES_ORDERS_CONTACTS' and tabschema='SCTID' ) THEN 
				
			EXECUTE IMMEDIATE 'CREATE TABLE SCTID.IBM_SALES_ORDERS_CONTACTS  (
					  ID VARCHAR(36 ) NOT NULL , 
					  ORDER_ID CHAR(36 ) NOT NULL , 
					  CONTACT_ID CHAR(36 ) NOT NULL , 
					  CONTACT_TYPE VARCHAR(7 ) NOT NULL , 
					  DATE_ENTERED TIMESTAMP , 
					  DATE_MODIFIED TIMESTAMP , 
					  DELETED SMALLINT NOT NULL )   
			  	  	  COMPRESS YES
			                  DATA CAPTURE CHANGES
			                  IN IBMSALESORDTS  INDEX IN IBMSALESORDIS
					 ORGANIZE BY ROW'; 
			
			EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBM_SORD_CNT_PK ON SCTID.IBM_SALES_ORDERS_CONTACTS (ID ASC) COMPRESS YES ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS' ;
			EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_SALES_ORDERS_CONTACTS	ADD CONSTRAINT IBM_SORD_CNT_PK PRIMARY KEY	(ID)';

END IF;


    IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_SALES_ORDERS_LEADS' and tabschema='SCTID' ) THEN 
		
		EXECUTE IMMEDIATE 'CREATE TABLE SCTID.IBM_SALES_ORDERS_LEADS  (
				  ID VARCHAR(36 ) NOT NULL , 
				  ORDER_ID CHAR(36 ) NOT NULL , 
				  LEAD_ID VARCHAR(100 ) , 
				  DATE_ENTERED TIMESTAMP , 
				  DATE_MODIFIED TIMESTAMP , 
				  DELETED SMALLINT NOT NULL )   
		  	  	  COMPRESS YES
		                  DATA CAPTURE CHANGES
		                  IN IBMSALESORDTS  INDEX IN IBMSALESORDIS
				 ORGANIZE BY ROW'; 
		
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBM_SORD_LD_PK ON SCTID.IBM_SALES_ORDERS_LEADS (ID ASC) COMPRESS YES ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS ';
		EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_SALES_ORDERS_LEADS ADD CONSTRAINT IBM_SORD_LD_PK PRIMARY KEY	(ID)';

END IF;


    IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_SALES_ORDERS_USERS' and tabschema='SCTID' ) THEN 

		EXECUTE IMMEDIATE 'CREATE TABLE SCTID.IBM_SALES_ORDERS_USERS  (
				  ID VARCHAR(36 ) NOT NULL , 
				  ORDER_ID CHAR(36 ) NOT NULL , 
				  USER_ID CHAR(36 ) , 
				  USER_TYPE VARCHAR(6 ) NOT NULL , 
				  DATE_ENTERED TIMESTAMP , 
				  DATE_MODIFIED TIMESTAMP , 
				  DELETED SMALLINT NOT NULL )   
		  	  	  COMPRESS YES
		                  DATA CAPTURE CHANGES
		                  IN IBMSALESORDTS  INDEX IN IBMSALESORDIS
				 ORGANIZE BY ROW'; 
		
		EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBM_SORD_USR_PK ON SCTID.IBM_SALES_ORDERS_USERS (ID ASC) COMPRESS YES  ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS' ;
		EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_SALES_ORDERS_USERS 	ADD CONSTRAINT IBM_SORD_USR_PK PRIMARY KEY	(ID)';

END IF; 

END @

--#SET TERMINATOR ;    
			
