/*DSW - Create Quote Tables*/

--#SET TERMINATOR @

BEGIN

     IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_QUOTES' and tabschema='SCTID' ) THEN 

			EXECUTE IMMEDIATE 'CREATE TABLE SCTID.IBM_QUOTES  (
					  ID CHAR(36 ) NOT NULL , 
					  NAME CHAR(36 ) NOT NULL , 
					  DELETED SMALLINT NOT NULL , 
					  CREATED_BY CHAR(36 ) , 
					  MODIFIED_USER_ID CHAR(36 ) , 
					  ASSIGNED_USER_ID CHAR(36 ) , 
					  SUBMITTER_ID CHAR(36 ) , 
					  DATE_ENTERED TIMESTAMP , 
					  DATE_MODIFIED TIMESTAMP , 
					  AGRMT_TYPE_CODE CHAR(4 ) , 
					  AGRMT_TYPE_CODE_DESCRIPTION VARCHAR(40 ) , 
					  ADD_DATE TIMESTAMP , 
					  MOD_DATE TIMESTAMP , 
					  CNTRY_CODE CHAR(3 ) NOT NULL , 
					  CNTRY_CODE_2 CHAR(5 ) , 
					  CREATOR_ID VARCHAR(256 ) , 
					  CREATOR_CNUM CHAR(36 ) , 
					  CURRNCY_CODE CHAR(3 ) NOT NULL , 
					  CMR_SYS_LOC_CODE VARCHAR(3 ) , 
					  CUST_NAME_FULL VARCHAR(536 ) , 
					  IBM_CLIENT_NUM CHAR(10 ) NOT NULL , 
					  IBM_CUST_NUM VARCHAR(10 ) , 
					  IDM_CNT_ID_SOLD_TO VARCHAR(100 ) , 
					  IDM_CNT_ID_TECH VARCHAR(100 ) , 
					  IDM_QUOTE_CNT_ID VARCHAR(100 ) , 
					  OPPRTNTY_NUM CHAR(36 ) , 
					  OPPRTNTY_OWNR_EMAIL_ADR VARCHAR(256 ) , 
					  QUOTE_CNT_ID INTEGER , 
					  QUOTE_EXP_DATE DATE , 
					  QUOTE_TITLE VARCHAR(80 ) , 
					  QUOTE_TYPE_CODE CHAR(10 ) , 
					  QUOTE_TYPE_CODE_DSCR CHAR(40 ) , 
					  QUOTE_ORVL_STAT_CODE CHAR(8 ) , 
					  QUOTE_ORVL_STAT_CODE_DSCR VARCHAR(40 ) , 
					  QUOTE_SAAS_MTHLY_STAT_CODE CHAR(8 ) , 
					  QUOTE_SAAS_MTHLY_STAT_CODE_DSCR VARCHAR(40 ) , 
					  QUOTE_SPECL_BID_STAT_CODE CHAR(8 ) , 
					  QUOTE_SPECL_BID_STAT_CODE_DSCR VARCHAR(40 ) , 
					  SAP_CNT_ID_SOLD_TO DECIMAL(10,0) , 
					  SAP_CNT_ID_TECH DECIMAL(10,0) , 
					  SAP_CTRCT_NUM CHAR(10 ) , 
					  SAP_ODS_MOD_DATE TIMESTAMP , 
					  SOLD_TO_CUST_NUM CHAR(10 ) NOT NULL , 
					  SUBMITTR_EMAIL VARCHAR(256 ) , 
					  SUBMITTR_CNUM CHAR(36 ) , 
					  LAST_UPDATING_SYSTEM_DATE TIMESTAMP NOT NULL , 
					  LAST_UPDATING_SYSTEM CHAR(50 ) NOT NULL , 
					  WEB_QUOTE_NUM CHAR(36 ) )   
					  COMPRESS YES 
					  DATA CAPTURE CHANGES 
					 IN IBMQUOTESTS  INDEX IN IBMQUOTESIS
					 ORGANIZE BY ROW'; 
			
			
				EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBMQUOTESPK ON SCTID.IBM_QUOTES (ID ASC) COMPRESS YES  ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS' ;
			
				EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_QUOTES ADD CONSTRAINT IBMQUOTESPK  PRIMARY KEY	(ID)';
				 END IF;

 IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_QUOTES_USERS' and tabschema='SCTID' ) THEN 

			EXECUTE IMMEDIATE 'CREATE TABLE SCTID.IBM_QUOTES_USERS  (
					  ID VARCHAR(36 ) NOT NULL , 
					  QUOTE_ID CHAR(36 ) NOT NULL , 
					  USER_ID CHAR(36 ) , 
					  USER_TYPE VARCHAR(6 ) NOT NULL , 
					  DATE_ENTERED TIMESTAMP NOT NULL , 
					  DATE_MODIFIED TIMESTAMP NOT NULL , 
					  DELETED SMALLINT NOT NULL )   
						COMPRESS YES 
						DATA CAPTURE CHANGES 
					 IN IBMQUOTESTS  INDEX IN IBMQUOTESIS
					 ORGANIZE BY ROW'; 
		
			EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBM_QT_USRPK ON SCTID.IBM_QUOTES_USERS (ID ASC) COMPRESS YES  ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS' ;
			EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_QUOTES_USERS 	ADD CONSTRAINT IBM_QT_USRPK PRIMARY KEY		(ID)';
			 END IF;


 IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_QUOTES_ACCOUNTS' and tabschema='SCTID' ) THEN 

			EXECUTE IMMEDIATE '
					CREATE TABLE SCTID.IBM_QUOTES_ACCOUNTS  (
				  ID VARCHAR(36 ) NOT NULL , 
				  QUOTE_ID CHAR(36 ) NOT NULL , 
				  ACCOUNT_ID CHAR(36 ) , 
				  DATE_ENTERED TIMESTAMP , 
				  DATE_MODIFIED TIMESTAMP , 
				  DELETED SMALLINT NOT NULL )   
				 COMPRESS YES 
				 DATA CAPTURE CHANGES 
				 IN IBMQUOTESTS  INDEX IN IBMQUOTESIS
				 ORGANIZE BY ROW' ; 
		
		
			EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBM_QT_ACCSPK ON SCTID.IBM_QUOTES_ACCOUNTS (ID ASC) COMPRESS YES  ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS' ;
		
		    EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_QUOTES_ACCOUNTS 	ADD CONSTRAINT IBM_QT_ACCSPK PRIMARY KEY(ID)';
		     END IF;

IF NOT  EXISTS (
    	select 1 from syscat.tables where tabname='IBM_QUOTES_CONTACTS' and tabschema='SCTID' ) THEN 

			EXECUTE IMMEDIATE '
					CREATE TABLE SCTID .IBM_QUOTES_CONTACTS  (
		 			  ID VARCHAR(36 ) NOT NULL , 
		 			  QUOTE_ID CHAR(36 ) NOT NULL , 
					  CONTACT_ID CHAR(36 ) NOT NULL , 
					  CONTACT_TYPE VARCHAR(7 ) NOT NULL , 
					  DATE_ENTERED TIMESTAMP , 
					  DATE_MODIFIED TIMESTAMP , 
					  DELETED SMALLINT NOT NULL )   
					 COMPRESS YES 
					 DATA CAPTURE CHANGES 
					 IN IBMQUOTESTS  INDEX IN IBMQUOTESIS
					 ORGANIZE BY ROW'; 

			EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX SCTID.IBM_QT_CONTPK ON SCTID.IBM_QUOTES_CONTACTS (ID ASC) COMPRESS YES  ALLOW REVERSE SCANS  COLLECT SAMPLED DETAILED STATISTICS ';
			EXECUTE IMMEDIATE 'ALTER TABLE SCTID.IBM_QUOTES_CONTACTS	ADD CONSTRAINT IBM_QT_CONTPK PRIMARY KEY	(ID)';

 END IF;

END @

--#SET TERMINATOR ;    

